[build]
  publish = "frontend/build"
  command = "cd frontend && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  # Security headers
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

  # Cache static assets
  for = "/static/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  # Cache HTML files
  for = "/*.html"
    [headers.values]
      Cache-Control = "public, max-age=0, must-revalidate" 