services:
  - type: web
    name: traveling-app-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # You'll need to set this manually
      - key: JWT_SECRET
        sync: false  # You'll need to set this manually
      - key: FRONTEND_URL
        sync: false  # You'll need to set this manually
    healthCheckPath: /health
    autoDeploy: true 